### ISSUE TITLE
App crashes in Auth fragment: API 23

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2159]
Logs-
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 32520
    java.lang.NoSuchMethodError: No virtual method getAnnotationsByType(Ljava/lang/Class;)[Ljava/lang/annotation/Annotation; in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.isRequiredByAnnotation(KotlinAnnotationIntrospector.kt:61)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:68)
        at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.access$hasRequiredMarker(KotlinAnnotationIntrospector.kt:23)
```

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Reason #2157

**Comment by liveHarshit** [comment]
> Reason #2157

I have checked by reverting changes in the PR, still crashing. Let me check again and confirm :+1:

**Comment by liveHarshit** [comment]
Tested. The app is crashing after PR #2157
