### ISSUE TITLE
Not able to create order: Working on frontend

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-attendee-android#2262]
![image](https://user-images.githubusercontent.com/27783786/62785601-995c9b80-bade-11e9-8af8-6eb695122b92.png)

TypeError
TypeError: '>' not supported between instances of 'NoneType' and 'int'

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 68, in sentry_patched_wsgi_app
    environ, start_response
  File "/app/.heroku/python/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 95, in __call__
    reraise(*_capture_exception(hub))
  File "/app/.heroku/python/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 53, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 93, in __call__
    rv = self.app(environ, start_response)
  File "/app/.heroku/python/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 67, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/app/__init__.py", line 72, in __call__
    return self.app(environ, start_response)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/app/app/api/helpers/permission_manager.py", line 488, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/app/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/app/app/api/helpers/permission_manager.py", line 18, in auth_required
    return view(*view_args, **view_kwargs)
  File "/app/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 312, in patch
    self._data_layer.update_object(obj, data, kwargs)
  File "/app/.heroku/src/flask-rest-jsonapi/flask_rest_jsonapi/data_layers/alchemy.py", line 126, in update_object
    self.before_update_object(obj, data, view_kwargs)
  File "/app/app/api/orders.py", line 313, in before_update_object
    check_billing_info(data)
  File "/app/app/api/orders.py", line 67, in check_billing_info
    if data.get('amount') > 0 and not data.get('is_billing_enabled'):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by liveHarshit** [comment]
@shreyanshdwivedi same error

**Comment by shreyanshdwivedi** [comment]
@liveHarshit I think it is yet not merged to deployment. 
@iamareebjamal can you  confirm this?

**Comment by liveHarshit** [comment]
> @liveHarshit I think it is yet not merged to deployment.
> @iamareebjamal can you confirm this?

I am using the dev instance.
```
TypeError
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by iamareebjamal** [comment]
It is merged in development so it should work on dev instance

**Comment by liveHarshit** [comment]
> It is merged in development so it should work on dev instance

Not working
![image](https://user-images.githubusercontent.com/27783786/62834457-6a733080-bc6a-11e9-9f3f-78b2c41943ad.png)

**Comment by shreyanshdwivedi** [comment]
@liveHarshit I checked this on my local. It is working fine
I created an attendee and then used it to create an order
And I checked for both paid and free tickets
Later I updated the status perfectly fine for the same payload - 
```
{
	"data": {
		"type": "order",
		"id":"155",
		"attributes": {
			"status": "completed",
			"order-notes": null
		}
	}
}
```
`Attendee creation`:
![Screenshot from 2019-08-11 23-21-03](https://user-images.githubusercontent.com/25428397/62837592-d7002680-bc8e-11e9-9b9e-0c8d6927939d.png)

`Order creation`:
![Screenshot from 2019-08-11 23-21-08](https://user-images.githubusercontent.com/25428397/62837594-dff0f800-bc8e-11e9-9a9e-eef3c1853c4a.png)

`Order updation`:
![Screenshot from 2019-08-11 23-21-14](https://user-images.githubusercontent.com/25428397/62837597-e54e4280-bc8e-11e9-9817-b5f13cc8f264.png)

**Comment by iamareebjamal** [comment]
Please try on heroku dev instance

**Comment by shreyanshdwivedi** [comment]
It's really weird, same payload are working fine on my local setup but they are producing error on heroku dev instance.
@iamareebjamal @liveHarshit  The dev instance is not updated till now -
Erros:
```
File "/app/app/api/orders.py", line 67, in check_billing_info
    if data.get('amount') > 0 and not data.get('is_billing_enabled'):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
I've updated this very line in my PR but it is not reflecting on heroku dev instance

**Comment by iamareebjamal** [comment]
Yeah, last build is on Aug 10. Strange

**Comment by iamareebjamal** [comment]
Deployed. Please check again. Still unsure why it wasn't deployed automatically

**Comment by liveHarshit** [comment]
> Deployed. Please check again. Still unsure why it wasn't deployed automatically

Yees, working :+1:
