### ISSUE TITLE
Events not loading

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-attendee-android#2363]
**Describe the bug**
Events are not loading in the front page and shimmer layout is shown only

**To Reproduce**

1. Open the app

**Expected behavior**
It should load the event

**Logs**
```
2019-09-25 22:31:28.285 12124-12124/com.eventyay.attendee E/EventsDataSource$createObservable: Fail on fetching page of events
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:139)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:119)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:142)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
        at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:452)
        at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:275)
        at org.fossasia.openevent.general.event.topic.EventTopicsDao_Impl.insertEventTopics(EventTopicsDao_Impl.java:75)
        at org.fossasia.openevent.general.event.EventService.updateFavorites(EventService.kt:78)
        at org.fossasia.openevent.general.event.EventService.access$updateFavorites(EventService.kt:23)
        at org.fossasia.openevent.general.event.EventService$getEventsByLocationPaged$1.apply(EventService.kt:71)
        at org.fossasia.openevent.general.event.EventService$getEventsByLocationPaged$1.apply(EventService.kt:23)
        at io.reactivex.internal.operators.single.SingleFlatMapPublisher$SingleFlatMapPublisherObserver.onSuccess(SingleFlatMapPublisher.java:96)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleFlatMapPublisher.subscribeActual(SingleFlatMapPublisher.java:66)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
The exception says everything. Are you compiling it or using the version from play store or fdroid?

**Comment by codedsun** [comment]
Compiling it on my local machine

**Comment by iamareebjamal** [comment]
Go ahead. Just increment the schema version

**Comment by refactor-droidyy** [comment]
Can i work on this issue.
